In [45]:
import copy, numpy as np

In [46]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [47]:
def sigmoid_derivative(output):
    return output / (1 - output)

In [48]:
binary_dim = 8
int2binary = {}

In [49]:
largest_number = pow(2, binary_dim)

In [50]:
binary = np.unpackbits(np.array([range(largest_number)], dtype=np.uint8).T, axis=1)
for i in binary:
    print(i)

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 1 1]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 1]
[0 0 0 0 0 1 1 0]
[0 0 0 0 0 1 1 1]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 1]
[0 0 0 0 1 0 1 0]
[0 0 0 0 1 0 1 1]
[0 0 0 0 1 1 0 0]
[0 0 0 0 1 1 0 1]
[0 0 0 0 1 1 1 0]
[0 0 0 0 1 1 1 1]
[0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 1]
[0 0 0 1 0 0 1 0]
[0 0 0 1 0 0 1 1]
[0 0 0 1 0 1 0 0]
[0 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 0]
[0 0 0 1 0 1 1 1]
[0 0 0 1 1 0 0 0]
[0 0 0 1 1 0 0 1]
[0 0 0 1 1 0 1 0]
[0 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 0]
[0 0 0 1 1 1 0 1]
[0 0 0 1 1 1 1 0]
[0 0 0 1 1 1 1 1]
[0 0 1 0 0 0 0 0]
[0 0 1 0 0 0 0 1]
[0 0 1 0 0 0 1 0]
[0 0 1 0 0 0 1 1]
[0 0 1 0 0 1 0 0]
[0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 0]
[0 0 1 0 0 1 1 1]
[0 0 1 0 1 0 0 0]
[0 0 1 0 1 0 0 1]
[0 0 1 0 1 0 1 0]
[0 0 1 0 1 0 1 1]
[0 0 1 0 1 1 0 0]
[0 0 1 0 1 1 0 1]
[0 0 1 0 1 1 1 0]
[0 0 1 0 1 1 1 1]
[0 0 1 1 0 0 0 0]
[0 0 1 1 0 0 0 1]
[0 0 1 1 0 0 1 0]
[0 0 1 1 0 0 1 1]
[0 0 1 1 0 1 0 0]
[0 0 1 1 0 1 0 1]
[0 0 1 1 0 1 1 0]
[0 0 1 1 0

In [51]:
for i in range(largest_number):
    int2binary[i] = binary[i]

In [53]:
for i in int2binary:
    print(int2binary[i])

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 1 1]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 1]
[0 0 0 0 0 1 1 0]
[0 0 0 0 0 1 1 1]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 1]
[0 0 0 0 1 0 1 0]
[0 0 0 0 1 0 1 1]
[0 0 0 0 1 1 0 0]
[0 0 0 0 1 1 0 1]
[0 0 0 0 1 1 1 0]
[0 0 0 0 1 1 1 1]
[0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 1]
[0 0 0 1 0 0 1 0]
[0 0 0 1 0 0 1 1]
[0 0 0 1 0 1 0 0]
[0 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 0]
[0 0 0 1 0 1 1 1]
[0 0 0 1 1 0 0 0]
[0 0 0 1 1 0 0 1]
[0 0 0 1 1 0 1 0]
[0 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 0]
[0 0 0 1 1 1 0 1]
[0 0 0 1 1 1 1 0]
[0 0 0 1 1 1 1 1]
[0 0 1 0 0 0 0 0]
[0 0 1 0 0 0 0 1]
[0 0 1 0 0 0 1 0]
[0 0 1 0 0 0 1 1]
[0 0 1 0 0 1 0 0]
[0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 0]
[0 0 1 0 0 1 1 1]
[0 0 1 0 1 0 0 0]
[0 0 1 0 1 0 0 1]
[0 0 1 0 1 0 1 0]
[0 0 1 0 1 0 1 1]
[0 0 1 0 1 1 0 0]
[0 0 1 0 1 1 0 1]
[0 0 1 0 1 1 1 0]
[0 0 1 0 1 1 1 1]
[0 0 1 1 0 0 0 0]
[0 0 1 1 0 0 0 1]
[0 0 1 1 0 0 1 0]
[0 0 1 1 0 0 1 1]
[0 0 1 1 0 1 0 0]
[0 0 1 1 0 1 0 1]
[0 0 1 1 0 1 1 0]
[0 0 1 1 0