In [1]:
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.optimizers import SGD, Adadelta, Adagrad
from keras.utils import np_utils, generic_utils
from keras.callbacks import EarlyStopping
from keras.layers.advanced_activations import PReLU, LeakyReLU
from keras.layers import Embedding,GRU,TimeDistributed,RepeatVector, LSTM, concatenate , Input, Reshape
from keras.preprocessing.text import one_hot
from keras.preprocessing import sequence
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import numpy as np
from keras import backend as K 
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model

Using TensorFlow backend.


In [2]:
max_caption_len = 3
vocab_size = 3

In [3]:
images = []
for i in range(2):
    images.append(img_to_array(load_img('/data/raw/screenshot.jpg', target_size=(224, 224))))
images = np.array(images, dtype=float)
images = preprocess_input(images)

In [4]:
html_input = np.array(
            [[[0., 0., 0.], #start
             [0., 0., 0.],
             [1., 0., 0.]],
             [[0., 0., 0.], #start <HTML>Hello World!</HTML>
             [1., 0., 0.],
             [0., 1., 0.]]])

next_words = np.array(
            [[0., 1., 0.], # <HTML>Hello World!</HTML>
             [0., 0., 1.]]) # end

In [5]:
VGG = VGG16(weights='imagenet', include_top=True)
VGG.trainable = False
vgg_out = RepeatVector(max_caption_len)(VGG.output)

In [6]:
language_input = Input(shape=(vocab_size, vocab_size))
language_model = LSTM(5, return_sequences=True)(language_input)

In [7]:
decoder = concatenate([vgg_out, language_model])
decoder = LSTM(5, return_sequences=False)(decoder)
decoder_output = Dense(vocab_size, activation='softmax')(decoder)
model = Model(inputs=[VGG.input, language_input], outputs=decoder_output)
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

In [8]:
model.fit([images, html_input], next_words, batch_size=2, shuffle=False, epochs=1000)

Epoch 1/1000
2/2 [==============================] - 3s - loss: 1.0958
Epoch 2/1000
2/2 [==============================] - 0s - loss: 1.0805
Epoch 3/1000
2/2 [==============================] - 0s - loss: 1.0758
Epoch 4/1000
2/2 [==============================] - 0s - loss: 1.0720
Epoch 5/1000
2/2 [==============================] - 0s - loss: 1.0686
Epoch 6/1000
2/2 [==============================] - 0s - loss: 1.0654
Epoch 7/1000
2/2 [==============================] - 0s - loss: 1.0624
Epoch 8/1000
2/2 [==============================] - 0s - loss: 1.0596
Epoch 9/1000
2/2 [==============================] - 0s - loss: 1.0568
Epoch 10/1000
2/2 [==============================] - 0s - loss: 1.0541
Epoch 11/1000
2/2 [==============================] - 0s - loss: 1.0515
Epoch 12/1000
2/2 [==============================] - 0s - loss: 1.0489
Epoch 13/1000
2/2 [==============================] - 0s - loss: 1.0463
Epoch 14/1000
2/2 [==============================] - 0s - loss: 1.0438
Epoch 15/1000
2

2/2 [==============================] - 0s - loss: 0.7868
Epoch 117/1000
2/2 [==============================] - 0s - loss: 0.7847
Epoch 118/1000
2/2 [==============================] - 0s - loss: 0.7825
Epoch 119/1000
2/2 [==============================] - 0s - loss: 0.7804
Epoch 120/1000
2/2 [==============================] - 0s - loss: 0.7784
Epoch 121/1000
2/2 [==============================] - 0s - loss: 0.7763
Epoch 122/1000
2/2 [==============================] - 0s - loss: 0.7743
Epoch 123/1000
2/2 [==============================] - 0s - loss: 0.7722
Epoch 124/1000
2/2 [==============================] - 0s - loss: 0.7702
Epoch 125/1000
2/2 [==============================] - 0s - loss: 0.7682
Epoch 126/1000
2/2 [==============================] - 0s - loss: 0.7662
Epoch 127/1000
2/2 [==============================] - 0s - loss: 0.7643
Epoch 128/1000
2/2 [==============================] - 0s - loss: 0.7623
Epoch 129/1000
2/2 [==============================] - 0s - loss: 0.7604
Epoch 1

2/2 [==============================] - 0s - loss: 0.5890
Epoch 231/1000
2/2 [==============================] - 0s - loss: 0.5868
Epoch 232/1000
2/2 [==============================] - 0s - loss: 0.5846
Epoch 233/1000
2/2 [==============================] - 0s - loss: 0.5824
Epoch 234/1000
2/2 [==============================] - 0s - loss: 0.5802
Epoch 235/1000
2/2 [==============================] - 0s - loss: 0.5779
Epoch 236/1000
2/2 [==============================] - 0s - loss: 0.5757
Epoch 237/1000
2/2 [==============================] - 0s - loss: 0.5734
Epoch 238/1000
2/2 [==============================] - 0s - loss: 0.5711
Epoch 239/1000
2/2 [==============================] - 0s - loss: 0.5688
Epoch 240/1000
2/2 [==============================] - 0s - loss: 0.5664
Epoch 241/1000
2/2 [==============================] - 0s - loss: 0.5641
Epoch 242/1000
2/2 [==============================] - 0s - loss: 0.5617
Epoch 243/1000
2/2 [==============================] - 0s - loss: 0.5593
Epoch 2

2/2 [==============================] - 0s - loss: 0.2635
Epoch 345/1000
2/2 [==============================] - 0s - loss: 0.2606
Epoch 346/1000
2/2 [==============================] - 0s - loss: 0.2577
Epoch 347/1000
2/2 [==============================] - 0s - loss: 0.2549
Epoch 348/1000
2/2 [==============================] - 0s - loss: 0.2520
Epoch 349/1000
2/2 [==============================] - 0s - loss: 0.2492
Epoch 350/1000
2/2 [==============================] - 0s - loss: 0.2464
Epoch 351/1000
2/2 [==============================] - 0s - loss: 0.2436
Epoch 352/1000
2/2 [==============================] - 0s - loss: 0.2408
Epoch 353/1000
2/2 [==============================] - 0s - loss: 0.2380
Epoch 354/1000
2/2 [==============================] - 0s - loss: 0.2352
Epoch 355/1000
2/2 [==============================] - 0s - loss: 0.2325
Epoch 356/1000
2/2 [==============================] - 0s - loss: 0.2298
Epoch 357/1000
2/2 [==============================] - 0s - loss: 0.2270
Epoch 3

2/2 [==============================] - 0s - loss: 0.0485
Epoch 459/1000
2/2 [==============================] - 0s - loss: 0.0477
Epoch 460/1000
2/2 [==============================] - 0s - loss: 0.0468
Epoch 461/1000
2/2 [==============================] - 0s - loss: 0.0461
Epoch 462/1000
2/2 [==============================] - 0s - loss: 0.0453
Epoch 463/1000
2/2 [==============================] - 0s - loss: 0.0446
Epoch 464/1000
2/2 [==============================] - 0s - loss: 0.0439
Epoch 465/1000
2/2 [==============================] - 0s - loss: 0.0432
Epoch 466/1000
2/2 [==============================] - 0s - loss: 0.0425
Epoch 467/1000
2/2 [==============================] - 0s - loss: 0.0418
Epoch 468/1000
2/2 [==============================] - 0s - loss: 0.0411
Epoch 469/1000
2/2 [==============================] - 0s - loss: 0.0404
Epoch 470/1000
2/2 [==============================] - 0s - loss: 0.0397
Epoch 471/1000
2/2 [==============================] - 0s - loss: 0.0391
Epoch 4

2/2 [==============================] - 0s - loss: 0.0080
Epoch 573/1000
2/2 [==============================] - 0s - loss: 0.0079
Epoch 574/1000
2/2 [==============================] - 0s - loss: 0.0078
Epoch 575/1000
2/2 [==============================] - 0s - loss: 0.0077
Epoch 576/1000
2/2 [==============================] - 0s - loss: 0.0076
Epoch 577/1000
2/2 [==============================] - 0s - loss: 0.0075
Epoch 578/1000
2/2 [==============================] - 0s - loss: 0.0073
Epoch 579/1000
2/2 [==============================] - 0s - loss: 0.0072
Epoch 580/1000
2/2 [==============================] - 0s - loss: 0.0071
Epoch 581/1000
2/2 [==============================] - 0s - loss: 0.0070
Epoch 582/1000
2/2 [==============================] - 0s - loss: 0.0069
Epoch 583/1000
2/2 [==============================] - 0s - loss: 0.0068
Epoch 584/1000
2/2 [==============================] - 0s - loss: 0.0067
Epoch 585/1000
2/2 [==============================] - 0s - loss: 0.0066
Epoch 5

2/2 [==============================] - 0s - loss: 0.0019
Epoch 687/1000
2/2 [==============================] - 0s - loss: 0.0019
Epoch 688/1000
2/2 [==============================] - 0s - loss: 0.0019
Epoch 689/1000
2/2 [==============================] - 0s - loss: 0.0019
Epoch 690/1000
2/2 [==============================] - 0s - loss: 0.0018
Epoch 691/1000
2/2 [==============================] - 0s - loss: 0.0018
Epoch 692/1000
2/2 [==============================] - 0s - loss: 0.0018
Epoch 693/1000
2/2 [==============================] - 0s - loss: 0.0018
Epoch 694/1000
2/2 [==============================] - 0s - loss: 0.0018
Epoch 695/1000
2/2 [==============================] - 0s - loss: 0.0017
Epoch 696/1000
2/2 [==============================] - 0s - loss: 0.0017
Epoch 697/1000
2/2 [==============================] - 0s - loss: 0.0017
Epoch 698/1000
2/2 [==============================] - 0s - loss: 0.0017
Epoch 699/1000
2/2 [==============================] - 0s - loss: 0.0017
Epoch 7

2/2 [==============================] - 0s - loss: 6.8900e-04
Epoch 798/1000
2/2 [==============================] - 0s - loss: 6.8280e-04
Epoch 799/1000
2/2 [==============================] - 0s - loss: 6.7668e-04
Epoch 800/1000
2/2 [==============================] - 0s - loss: 6.7158e-04
Epoch 801/1000
2/2 [==============================] - 0s - loss: 6.6559e-04
Epoch 802/1000
2/2 [==============================] - 0s - loss: 6.5965e-04
Epoch 803/1000
2/2 [==============================] - 0s - loss: 6.5384e-04
Epoch 804/1000
2/2 [==============================] - 0s - loss: 6.4805e-04
Epoch 805/1000
2/2 [==============================] - 0s - loss: 6.4334e-04
Epoch 806/1000
2/2 [==============================] - 0s - loss: 6.3744e-04
Epoch 807/1000
2/2 [==============================] - 0s - loss: 6.3183e-04
Epoch 808/1000
2/2 [==============================] - 0s - loss: 6.2676e-04
Epoch 809/1000
2/2 [==============================] - 0s - loss: 6.2127e-04
Epoch 810/1000
2/2 [=======

2/2 [==============================] - 0s - loss: 2.7568e-04
Epoch 906/1000
2/2 [==============================] - 0s - loss: 2.7344e-04
Epoch 907/1000
2/2 [==============================] - 0s - loss: 2.7118e-04
Epoch 908/1000
2/2 [==============================] - 0s - loss: 2.6903e-04
Epoch 909/1000
2/2 [==============================] - 0s - loss: 2.6692e-04
Epoch 910/1000
2/2 [==============================] - 0s - loss: 2.6468e-04
Epoch 911/1000
2/2 [==============================] - 0s - loss: 2.6244e-04
Epoch 912/1000
2/2 [==============================] - 0s - loss: 2.6030e-04
Epoch 913/1000
2/2 [==============================] - 0s - loss: 2.5815e-04
Epoch 914/1000
2/2 [==============================] - 0s - loss: 2.5603e-04
Epoch 915/1000
2/2 [==============================] - 0s - loss: 2.5395e-04
Epoch 916/1000
2/2 [==============================] - 0s - loss: 2.5183e-04
Epoch 917/1000
2/2 [==============================] - 0s - loss: 2.4983e-04
Epoch 918/1000
2/2 [=======

In [50]:
start_token = [1., 0., 0.]
sentence = np.zeros((1, 3, 3))
sentence[0][2] = start_token

In [51]:
first_word = model.predict([np.array([images[1]]), sentence])

In [52]:
sentence[0][1] = start_token
sentence[0][2] = np.round(first_word)

In [53]:
second_word = model.predict([np.array([images[1]]), sentence])

In [54]:
sentence[0][0] = start_token
sentence[0][1] = np.round(first_word)
sentence[0][2] = np.round(second_word)

In [55]:
print(sentence)

[[[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]]
