In [1]:
import copy, numpy as np

In [20]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [31]:
output / (1 - output)

7.38905609893


In [28]:
def sigmoid_derivative(output):
    return output/(1 - output)
print(sigmoid_derivative(0.5))

1.0


In [10]:
int2binary = {}
binary_dim = 8

In [19]:
largest_number = pow(2, binary_dim)
binary = np.unpackbits(np.array(range(largest_number]).T, dtype=uint8, axis))
for i in range(largest_number):
    int2binary[i] = binary[i]

In [6]:
alpha = 0.1
input_dim = 2
hidden_dim = 16
output_dim = 1

In [7]:
print(type(binary))

<class 'numpy.ndarray'>


In [9]:
for i in int2binary:
    print(int2binary[i])

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 1 1]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 1]
[0 0 0 0 0 1 1 0]
[0 0 0 0 0 1 1 1]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 1]
[0 0 0 0 1 0 1 0]
[0 0 0 0 1 0 1 1]
[0 0 0 0 1 1 0 0]
[0 0 0 0 1 1 0 1]
[0 0 0 0 1 1 1 0]
[0 0 0 0 1 1 1 1]
[0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 1]
[0 0 0 1 0 0 1 0]
[0 0 0 1 0 0 1 1]
[0 0 0 1 0 1 0 0]
[0 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 0]
[0 0 0 1 0 1 1 1]
[0 0 0 1 1 0 0 0]
[0 0 0 1 1 0 0 1]
[0 0 0 1 1 0 1 0]
[0 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 0]
[0 0 0 1 1 1 0 1]
[0 0 0 1 1 1 1 0]
[0 0 0 1 1 1 1 1]
[0 0 1 0 0 0 0 0]
[0 0 1 0 0 0 0 1]
[0 0 1 0 0 0 1 0]
[0 0 1 0 0 0 1 1]
[0 0 1 0 0 1 0 0]
[0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 0]
[0 0 1 0 0 1 1 1]
[0 0 1 0 1 0 0 0]
[0 0 1 0 1 0 0 1]
[0 0 1 0 1 0 1 0]
[0 0 1 0 1 0 1 1]
[0 0 1 0 1 1 0 0]
[0 0 1 0 1 1 0 1]
[0 0 1 0 1 1 1 0]
[0 0 1 0 1 1 1 1]
[0 0 1 1 0 0 0 0]
[0 0 1 1 0 0 0 1]
[0 0 1 1 0 0 1 0]
[0 0 1 1 0 0 1 1]
[0 0 1 1 0 1 0 0]
[0 0 1 1 0 1 0 1]
[0 0 1 1 0 1 1 0]
[0 0 1 1 0